/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CalculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorForm
     */
    
    double so1;
    double so2;
    String cong = " + ";
    String tru = " - ";
    String nhan = " * ";
    String chia = " / ";
    
    public CalculatorForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        runTitle();
    }
    
    private void runTitle(){
        Thread t = new Thread(){
            @Override
            public void run() {
                int i = 0;
                String text = lbl_title.getText();
                while (true) {                    
                    String c1 = text.substring(i, i + 1);
                    String c2 = text.substring(i, text.length());
                    text += c1;
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        break;
                    }
                    lbl_title.setText(c2);
                    i++;
                }
            }
        };
        t.start();
    }
    
    private boolean checkNull(){
        if (txt.getText().isEmpty()) {
            txt.setBackground(Color.yellow);
            showMes();
            txt.requestFocus();
            return true;
        }
        txt.setBackground(Color.white);
        return false;
    }
    
    private void showMes(){
        JOptionPane.showMessageDialog(this, "Please input your calculation");
    }
    
    private void getButtonText(JButton btn){
        String text = txt.getText();
        text += btn.getText();
        txt.setText(text);
    }
    
    private void record(JButton btn) {
        if (txt.getText().length() < 5) {
            return;
        }
        lbl_record.setText(lbl_record.getText() + btn.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_1x = new javax.swing.JButton();
        btn_x2 = new javax.swing.JButton();
        btn_sqrt = new javax.swing.JButton();
        btn_chia = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn_nhan = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn_tru = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn_cong = new javax.swing.JButton();
        btn_am = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn_thapphan = new javax.swing.JButton();
        btn_kq = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        lbl_record = new javax.swing.JLabel();

        jButton9.setText("jButton9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(0, 0, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("ELECTRONIC CALCULATOR   ");

        txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout(0, 4, 5, 5));

        btn_1x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_1x.setText("1/x");
        btn_1x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1xActionPerformed(evt);
            }
        });
        jPanel2.add(btn_1x);

        btn_x2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_x2.setText("x2");
        btn_x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_x2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_x2);

        btn_sqrt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_sqrt.setText("sqrt(x)");
        btn_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqrtActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sqrt);

        btn_chia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_chia.setText("/");
        btn_chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chiaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_chia);

        btn7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        btn_nhan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_nhan.setText("*");
        btn_nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhanActionPerformed(evt);
            }
        });
        jPanel2.add(btn_nhan);

        btn4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btn_tru.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_tru.setText("-");
        btn_tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_truActionPerformed(evt);
            }
        });
        jPanel2.add(btn_tru);

        btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btn_cong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cong.setText("+");
        btn_cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_congActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cong);

        btn_am.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_am.setText("+/-");
        btn_am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_amActionPerformed(evt);
            }
        });
        jPanel2.add(btn_am);

        btn0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0);

        btn_thapphan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_thapphan.setText(".");
        btn_thapphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thapphanActionPerformed(evt);
            }
        });
        jPanel2.add(btn_thapphan);

        btn_kq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_kq.setText("=");
        btn_kq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kqActionPerformed(evt);
            }
        });
        jPanel2.add(btn_kq);

        btn_reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_reset.setText("C");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        lbl_record.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_record.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_record, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_record, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        try {
            txt.setText("");
            lbl_record.setText("");
            txt.requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_1xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1xActionPerformed
        try {
            if (checkNull()) {
                return;
            }
            so1 = Double.parseDouble(txt.getText());
            txt.setText(1 / so1 + "");
        } catch (Exception e) {
            showMes();
        }
    }//GEN-LAST:event_btn_1xActionPerformed

    private void btn_x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_x2ActionPerformed
        try {
            if (checkNull()) {
                return;
            }
            so1 = Double.parseDouble(txt.getText());
            txt.setText(so1 * so1 + "");
        } catch (Exception e) {
            showMes();
        }
    }//GEN-LAST:event_btn_x2ActionPerformed

    private void btn_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqrtActionPerformed
        try {
            if (checkNull()) {
                return;
            }
            so1 = Double.parseDouble(txt.getText());
            txt.setText(Math.sqrt(so1)+"");
        } catch (Exception e) {
            showMes();
        }
    }//GEN-LAST:event_btn_sqrtActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        try {
            getButtonText(btn1);
            record(btn1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        try {
            getButtonText(btn0);
            record(btn0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        try {
            getButtonText(btn2);
            record(btn2);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        try {
            getButtonText(btn3);
            record(btn3);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        try {
            getButtonText(btn4);
            record(btn4);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        try {
            getButtonText(btn5);
            record(btn5);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        try {
            getButtonText(btn6);
            record(btn6);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        try {
            getButtonText(btn7);
            record(btn7);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        try {
            getButtonText(btn8);
            record(btn8);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        try {
            getButtonText(btn9);
            record(btn9);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn_amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_amActionPerformed
        try {
            if (checkNull()) {
                return;
            }
            if (txt.getText().startsWith("-")) {
                txt.setText(txt.getText().substring(1));
                return;
            }
            String text = "-";
            txt.setText(text + txt.getText());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_amActionPerformed

    private void btn_congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_congActionPerformed
        try {
            if (checkNull()) {
                return;
            }
            if (txt.getText().contains(cong)) {
                return;
            }
            if (txt.getText().contains(tru)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            if (txt.getText().contains(nhan)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            if (txt.getText().contains(chia)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            lbl_record.setText("");
            lbl_record.setText(cong);
            txt.setText(txt.getText() + cong);
        } catch (Exception e) {
            showMes();
        }
    }//GEN-LAST:event_btn_congActionPerformed

    private void btn_truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_truActionPerformed
        try {
            if (checkNull()) {
                return;
            }
            if (txt.getText().contains(tru)) {
                return;
            }
            if (txt.getText().contains(cong)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            if (txt.getText().contains(nhan)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            if (txt.getText().contains(chia)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            lbl_record.setText("");
            lbl_record.setText(tru);
            txt.setText(txt.getText() + tru);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_truActionPerformed

    private void btn_nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhanActionPerformed
        try {
            if (checkNull()) {
                return;
            }
            if (txt.getText().contains(nhan)) {
                return;
            }
            if (txt.getText().contains(cong)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            if (txt.getText().contains(tru)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            if (txt.getText().contains(chia)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            lbl_record.setText("");
            lbl_record.setText(nhan);
            txt.setText(txt.getText() + nhan);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_nhanActionPerformed

    private void btn_chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chiaActionPerformed
        try {
            if (checkNull()) {
                return;
            }
            if (txt.getText().contains(chia)) {
                return;
            }
            if (txt.getText().contains(tru)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            if (txt.getText().contains(nhan)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            if (txt.getText().contains(cong)) {
                txt.setText(txt.getText().substring(0,txt.getText().length() - 3));
            }
            lbl_record.setText("");
            lbl_record.setText(chia);
            txt.setText(txt.getText() + chia);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_chiaActionPerformed

    private void btn_kqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kqActionPerformed
        try {
            if (checkNull()) {
                return;
            }
            if (lbl_record.getText().length() > 3) {
                txt.setText(txt.getText() + " " + lbl_record.getText());
            }
            int vtd = txt.getText().indexOf(" ");
            int vtc = txt.getText().lastIndexOf(" ");
            so1 = Double.parseDouble(txt.getText().substring(0, vtd));
            so2 = Double.parseDouble(txt.getText().substring(vtc + 1));
            if (txt.getText().contains(cong)) {
                txt.setText(so1 + so2 + "");
            }
            if (txt.getText().contains(tru)) {
                txt.setText(so1 - so2 + "");
            }
            if (txt.getText().contains(nhan)) {
                txt.setText(so1 * so2 + "");
            }
            if (txt.getText().contains(chia)) {
                txt.setText(so1 / so2 + "");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_kqActionPerformed

    private void btn_thapphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thapphanActionPerformed
        try {
            if (txt.getText().isEmpty()) {
                txt.setText("0.");
                return;
            }
            if (txt.getText().contains(cong) || txt.getText().contains(tru) || txt.getText().contains(nhan) || txt.getText().contains(chia)) {
                txt.setText(txt.getText() + ".");
            }
            if (txt.getText().contains(".")) {
                return;
            }
            txt.setText(txt.getText() + ".");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_thapphanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalculatorForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn_1x;
    private javax.swing.JButton btn_am;
    private javax.swing.JButton btn_chia;
    private javax.swing.JButton btn_cong;
    private javax.swing.JButton btn_kq;
    private javax.swing.JButton btn_nhan;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sqrt;
    private javax.swing.JButton btn_thapphan;
    private javax.swing.JButton btn_tru;
    private javax.swing.JButton btn_x2;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_record;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
