/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subSwing;

import jSupport.Validator;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objects.BangDiem;
import objects.QuanLyBangDiem;
import objects.QuanLySinhVien;
import objects.SinhVien;

/**
 *
 * @author DaiAustinYersin
 */
public class JPanel_QuanLyDiem extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_QuanLyDiem
     */
    mainJFrame.MainJFrame parent;
    DefaultTableModel tableModel = new DefaultTableModel();
    List<BangDiem> list = new ArrayList<>();
    int index;
    StringBuilder sb;

    public JPanel_QuanLyDiem() {
        initComponents();

        tableModel = (DefaultTableModel) tblQLDiem.getModel();
        loadDataToTable(3);
        if (list.size() > 0) {
            index = 0;
            display();
        }
        jSupport.JThread.runText(lblQLDiem);
    }

    private void loadDataToTable(int top) {
        tableModel.setRowCount(0);
        try {
            QuanLyBangDiem qlbd = new QuanLyBangDiem();
            list = qlbd.findTop(top);
            for (BangDiem bd : list) {
                NumberFormat format = new DecimalFormat("#0.00");
                String diemTB = format.format((bd.getTiengAnh() + bd.getTinHoc() + bd.getGDTC()) / 3);
                tableModel.addRow(new Object[]{
                    bd.getMaSinhVien(), bd.getHoTen(), bd.getTiengAnh(), bd.getTinHoc(), bd.getGDTC(),
                    diemTB
                });
            }
            tableModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            jSupport.ShowDialog.showError(parent, "Lỗi", e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQLSV = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        btnLuu = new javax.swing.JButton();
        lblQLDiem = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFindMaSV = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtTgAnh = new javax.swing.JTextField();
        txtTin = new javax.swing.JTextField();
        txtGDTC = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        lblDiemTB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLDiem = new javax.swing.JTable();
        btnTop3 = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 148, 6));

        pnlQLSV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save1.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        lblQLDiem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQLDiem.setForeground(new java.awt.Color(51, 51, 255));
        lblQLDiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLDiem.setText("QUẢN LÝ ĐIỂM  ");

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del1.jpg"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update1.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add1.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel2.setText("Mã sinh viên:");

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find.jpg"))); // NOI18N
        btnFind.setText("Tìm kiếm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFindMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnFind)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFindMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Mã sinh viên:");

        jLabel5.setText("Tiếng Anh:");

        jLabel6.setText("Tin học:");

        jLabel7.setText("Giáo dục thể chất:");

        lblHoTen.setForeground(new java.awt.Color(0, 0, 255));
        lblHoTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtMaSV.setForeground(new java.awt.Color(0, 0, 255));
        txtMaSV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaSVFocusLost(evt);
            }
        });

        txtTgAnh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTgAnhFocusLost(evt);
            }
        });

        txtTin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTgAnhFocusLost(evt);
            }
        });

        txtGDTC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTgAnhFocusLost(evt);
            }
        });

        jLabel9.setText("Điểm trung bình:");

        lblDiemTB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDiemTB.setForeground(new java.awt.Color(255, 51, 51));
        lblDiemTB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(txtTgAnh)
                            .addComponent(txtTin)
                            .addComponent(txtGDTC)
                            .addComponent(lblHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDiemTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTgAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGDTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiemTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("3 sinh viên có điểm cao nhất");

        tblQLDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Họ tên", "Tiếng Anh", "Tin học", "Giáo dục thể chất", "Điểm trung bình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQLDiem.setRowHeight(25);
        tblQLDiem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblQLDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLDiem);

        btnTop3.setText("TOP 3");
        btnTop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTop3ActionPerformed(evt);
            }
        });

        btnShowAll.setText("Hiện tất cả");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQLSVLayout = new javax.swing.GroupLayout(pnlQLSV);
        pnlQLSV.setLayout(pnlQLSVLayout);
        pnlQLSVLayout.setHorizontalGroup(
            pnlQLSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLSVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlQLSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQLDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator6)
                    .addGroup(pnlQLSVLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlQLSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 253, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLSVLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlQLSVLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pnlQLSVLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapNhat, btnLamMoi, btnLuu, btnXoa});

        pnlQLSVLayout.setVerticalGroup(
            pnlQLSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlQLSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlQLSVLayout.createSequentialGroup()
                        .addComponent(btnLamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTop3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShowAll))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlQLSVLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCapNhat, btnLamMoi, btnLuu, btnShowAll, btnTop3, btnXoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(pnlQLSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(pnlQLSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblQLDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLDiemMouseClicked
        try {
            index = tblQLDiem.getSelectedRow();
            display();
        } catch (Exception e) {
            e.printStackTrace();
            jSupport.ShowDialog.showError(parent, "Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_tblQLDiemMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (Validator()) {
            return;
        }
        try {
            BangDiem bd = new BangDiem();
            bd.setMaSinhVien(txtMaSV.getText());
            bd.setTiengAnh(Double.parseDouble(txtTgAnh.getText()));
            bd.setTinHoc(Double.parseDouble(txtTin.getText()));
            bd.setGDTC(Double.parseDouble(txtGDTC.getText()));

            QuanLyBangDiem qlbd = new QuanLyBangDiem();
            if (qlbd.findByMaSV(txtMaSV.getText()) != null) {
                if (jSupport.ShowDialog.showConfirm(parent, "Xác nhận", "Bạn có muốn cập nhật điểm sinh viên mã " + txtMaSV.getText() + " không?") != JOptionPane.YES_OPTION) {
                    return;
                }
                if (qlbd.update(bd)) {
                    loadDataToTable(3);
                    jSupport.ShowDialog.showMessage(parent, "Thông báo", "Dữ liệu sinh viên mã " + txtMaSV.getText() + " đã được cập nhật");
                } else {
                    jSupport.ShowDialog.showMessage(parent, "Thông báo", "Dữ liệu chưa được cập nhật do lỗi");
                }
                return;
            }

            if (qlbd.insert(bd)) {
                list.add(bd);
                NumberFormat format = new DecimalFormat("#0.00");
                String diemTB = format.format((bd.getTiengAnh() + bd.getTinHoc() + bd.getGDTC()) / 3);
                tableModel.addRow(new Object[]{
                    bd.getMaSinhVien(), bd.getHoTen(), bd.getTiengAnh(), bd.getTinHoc(), bd.getGDTC(),
                    diemTB
                });
                loadDataToTable(3);
                jSupport.ShowDialog.showMessage(parent, "Thông báo", "Dữ liệu sinh viên mã " + txtMaSV.getText() + " đã được lưu");
            } else {
                jSupport.ShowDialog.showMessage(parent, "Thông báo", "Bảng điểm chưa được lưu do lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
            jSupport.ShowDialog.showError(parent, "Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private boolean Validator() {
        sb = new StringBuilder();
        Validator.checkNull(txtMaSV, "Chưa nhập mã sinh viên", sb);
        Validator.checkDiem(txtTgAnh, sb, "Điểm phải trong khoảng 1-10", "Điểm phải là một số", "Điểm tiếng Anh chưa nhập");
        Validator.checkDiem(txtTin, sb, "Điểm phải trong khoảng 1-10", "Điểm phải là một số", "Điểm Tin học chưa nhập");
        Validator.checkDiem(txtGDTC, sb, "Điểm phải trong khoảng 1-10", "Điểm phải là một số", "Điểm GDTC chưa nhập");
        if (sb.length() > 0) {
            jSupport.ShowDialog.showError(parent, "Dữ liệu không hợp lệ", sb.toString());
            return true;
        }
        return false;
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        sb = new StringBuilder();
        Validator.checkNull(txtMaSV, "Mã sinh viên chưa nhập", sb);
        if (sb.length() > 0) {
            jSupport.ShowDialog.showError(parent, "Dữ liệu không hợp lệ", sb.toString());
            return;
        }
        try {
            QuanLyBangDiem qlbd = new QuanLyBangDiem();
            BangDiem bd = qlbd.findByMaSV(txtMaSV.getText());
            if (bd == null) {
                jSupport.ShowDialog.showMessage(parent, "Mã sinh viên không tồn tại", "Dữ liệu không hợp lệ");
                return;
            }
            if (jSupport.ShowDialog.showConfirm(parent, "Xác nhận", "Bạn có muốn xóa hay không?") != JOptionPane.YES_OPTION) {
                return;
            }
            if (qlbd.deleteByMaSV(bd)) {
                jSupport.ShowDialog.showError(parent, "Thông báo", "Điểm của sinh viên đã được xóa");
                loadDataToTable(3);
            } else {
                jSupport.ShowDialog.showError(parent, "Thông báo", "Điểm của sinh viên không được xóa do lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
            jSupport.ShowDialog.showError(parent, "Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        btnLuuActionPerformed(evt);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtMaSVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaSVFocusLost
        sb = new StringBuilder();
        Validator.checkNull(txtMaSV, "Mã sinh viên chưa nhập", sb);
        if (sb.length() > 0) {
            jSupport.ShowDialog.showError(parent, "Dữ liệu không hợp lệ", sb.toString());
            return;
        }
        try {
            QuanLySinhVien qlsv = new QuanLySinhVien();
            SinhVien sv = qlsv.selectByMaSV(txtMaSV.getText());
            if (sv != null) {
                lblHoTen.setText(sv.getHoTen());
            } else {
                lblHoTen.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
            jSupport.ShowDialog.showError(parent, "Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_txtMaSVFocusLost

    private void txtTgAnhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTgAnhFocusLost
        try {
            if (txtTgAnh.getText().isEmpty()
                    || txtTin.getText().isEmpty()
                    || txtGDTC.getText().isEmpty()) {
                return;
            }
            float ta = Float.parseFloat(txtTgAnh.getText());
            float it = Float.parseFloat(txtTin.getText());
            float pt = Float.parseFloat(txtGDTC.getText());

            float avg = (ta + it + pt) / 3;

            String st = String.format("%.2f", avg);
            lblDiemTB.setText(st);
        } catch (Exception e) {
            e.printStackTrace();
            jSupport.ShowDialog.showError(parent, "Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_txtTgAnhFocusLost

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try {
            tableModel.setRowCount(0);
            QuanLyBangDiem qlbd = new QuanLyBangDiem();
            if (qlbd.findByMaSV(txtFindMaSV.getText()) != null) {
                BangDiem bd = qlbd.findByMaSV(txtFindMaSV.getText());
                NumberFormat format = new DecimalFormat("#0.00");
                String diemTB = format.format((bd.getTiengAnh() + bd.getTinHoc() + bd.getGDTC()) / 3);
                tableModel.addRow(new Object[]{
                    bd.getMaSinhVien(), bd.getHoTen(), bd.getTiengAnh(), bd.getTinHoc(), bd.getGDTC(),
                    diemTB
                });
                index = 0;
                display();
            } else {
                clearForm();
                jSupport.ShowDialog.showMessage(parent, "Dữ liệu không hợp lệ", "Không tìm thấy thông tin sinh viên có mã " + txtFindMaSV.getText());
            }
        } catch (Exception e) {
            e.printStackTrace();
            jSupport.ShowDialog.showError(parent, "Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnTop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTop3ActionPerformed
        try {
            loadDataToTable(3);
            if (list.size() > 0) {
                index = 0;
                display();
            }
        } catch (Exception e) {
            e.printStackTrace();
            jSupport.ShowDialog.showError(parent, "Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_btnTop3ActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        try {
            tableModel.setRowCount(0);
            QuanLyBangDiem qlbd = new QuanLyBangDiem();
            list = qlbd.findAll();
            for (BangDiem bd : list) {
                NumberFormat format = new DecimalFormat("#0.00");
                String diemTB = format.format((bd.getTiengAnh() + bd.getTinHoc() + bd.getGDTC()) / 3);
                tableModel.addRow(new Object[]{
                    bd.getMaSinhVien(), bd.getHoTen(), bd.getTiengAnh(), bd.getTinHoc(), bd.getGDTC(),
                    diemTB
                });
            }
            if (list.size() > 0) {
                index = 0;
                display();
            }
        } catch (Exception e) {
            e.printStackTrace();
            jSupport.ShowDialog.showError(parent, "Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void display() {
        tblQLDiem.setRowSelectionInterval(index, index);
        lblHoTen.setText(tableModel.getValueAt(index, 1).toString());
        txtMaSV.setText(tableModel.getValueAt(index, 0).toString());
        txtTgAnh.setText(tableModel.getValueAt(index, 2).toString());
        txtTin.setText(tableModel.getValueAt(index, 3).toString());
        txtGDTC.setText(tableModel.getValueAt(index, 4).toString());
        lblDiemTB.setText(tableModel.getValueAt(index, 5).toString());
    }

    private void clearForm() {
        lblHoTen.setText("");
        lblDiemTB.setText("");
        txtMaSV.setText("");
        txtTgAnh.setText("");
        txtTin.setText("");
        txtGDTC.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnTop3;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblDiemTB;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblQLDiem;
    private javax.swing.JPanel pnlQLSV;
    private javax.swing.JTable tblQLDiem;
    private javax.swing.JTextField txtFindMaSV;
    private javax.swing.JTextField txtGDTC;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTgAnh;
    private javax.swing.JTextField txtTin;
    // End of variables declaration//GEN-END:variables
}
